---
addons:
  - (( append ))
  - name: loggregator_agent
    include:
      stemcell:
        - os: ubuntu-xenial

    exclude:
      jobs:
        - { release: cf-smoke-tests, name: smoke_tests }

    jobs:
      - name: loggregator_agent
        release: loggregator-agent
        properties:
          grpc_port: 3459
          disable_udp: true
          loggregator:
            tls:
              ca_cert:    (( grab meta.certs.loggregator.agent.ca_cert ))
              agent:
                cert:     (( grab meta.certs.loggregator.agent.cert ))
                key:      (( grab meta.certs.loggregator.agent.key ))
          deployment:     (( grab name ))
          metrics:
            server_name:  loggregator_agent_metrics
            .:            (( inject meta.certs.metrics.loggregator_agent_metrics_tls ))

      - name: prom_scraper
        release:  loggregator-agent
        properties:
          scrape:
            tls:          (( grab meta.certs.metrics.prom_scraper_scrape_tls ))
          metrics:
            server_name:  prom_scraper_metrics
            .:            (( inject meta.certs.metrics.prom_scraper_metrics_tls ))

# - name: forwarder_agent
#   release: loggregator-agent
#   include:
#     stemcell:
#     - os: ubuntu-xenial
#   jobs:
#   - name: loggr-forwarder-agent
#     release: loggregator-agent
#     properties:
#       tls:
#         ca_cert:    (( grab meta.certs.loggregator.agent.ca_cert ))
#         cert:     (( grab meta.certs.loggregator.agent.cert ))
#         key:      (( grab meta.certs.loggregator.agent.key ))
#       metrics:
#         server_name: forwarder_agent_metrics
#         .:            (( inject meta.certs.metrics.loggregator_agent_metrics_tls ))


