---
meta:
  cell:
    trusted_cas:
      - (( grab meta.certs.diego_instance_identity_ca.ca_cert ))
      # - ((credhub_tls.ca)) #FIXME - will be added once credhub is added
      - (( grab meta.certs.uaa.ca.cert ))
  diego_rep_client_tls:
    ca_cert:     (( grab meta.certs.cf_internal.diego_rep_client.ca_cert ))
    client_cert: (( grab meta.certs.cf_internal.diego_rep_client.cert ))
    client_key:  (( grab meta.certs.cf_internal.diego_rep_client.key ))
    require_tls: true
  diego_loggregator_client_tls:
    .: (( inject meta.certs.loggregator.agent )) # .ca_cert, .cert & .key
    use_v2_api: true

  cc:
    diego:
      # These are here to ensure that we can augment them if cflinuxfs2
      # (for backwards-compatibility) is enabled.  These are the defaults
      # from the upstream BOSH release, made explicit here.
      #
      lifecycle_bundles:
        buildpack/cflinuxfs3: buildpack_app_lifecycle/buildpack_app_lifecycle.tgz
        docker:               docker_app_lifecycle/docker_app_lifecycle.tgz
      droplet_destinations:
        cflinuxfs3: /home/vcap
params:
  trusted_cas: []
  evacuation_timeout: 600

instance_groups:
  - name: scheduler
    jobs:
    - name: route_emitter
      release: diego
      properties:
        bpm:
          enabled: true
        locks:
          consul:
            enabled: false
        loggregator: (( grab meta.diego_loggregator_client_tls ))
        diego:
          route_emitter:
            healthcheck_address: 127.0.0.1:17012 # to avoid conflict colocating with stager
            bbs: (( grab meta.diego_bbs_client_tls ))
        uaa:
          ca_cert: (( grab meta.certs.uaa.ca.cert ))
          client_secret: (( grab meta.uaa.tcp_emitter_secret ))
    - name: auctioneer
      release: diego
      properties:
        enable_consul_service_registration: false
        diego:
          auctioneer:
            skip_consul_lock: true
            ca_cert:     (( grab meta.certs.cf_internal.diego_auctioneer_server.ca_cert ))
            server_cert: (( grab meta.certs.cf_internal.diego_auctioneer_server.cert ))
            server_key:  (( grab meta.certs.cf_internal.diego_auctioneer_server.key ))
            bbs:         (( grab meta.diego_bbs_client_tls ))
            rep:         (( grab meta.diego_rep_client_tls ))
        loggregator: (( grab meta.diego_loggregator_client_tls ))
      - name: cc_deployment_updater
        release: capi
        properties:
          ccdb: (( grab meta.ccdb ))
          cc:
            db_encryption_key:             (( vault meta.vault "/cc:db_encryption_key" ))
            temporary_disable_deployments: (( grab meta.cc.temporary_disable_deployments ))
            mutual_tls:                    (( grab meta.certs.cf_internal.cc_tls ))
      - name: statsd_injector
        release: statsd-injector
        properties: (( grab meta.statsd_injector ))


      - name: cloud_controller_clock
        release: capi
        properties:
          system_domain: (( grab params.system_domain ))

          ccdb: (( grab meta.ccdb ))
          cc:   (( grab meta.cc ))

          logger_endpoint:
            port: (( grab params.logger_port ))

          uaa:
            ca_cert: (( grab meta.certs.uaa.ca.cert ))
            clients:
              cc-service-dashboards:
                scope: openid,cloud_controller_service_permissions.read
                secret: (( grab meta.uaa.cc_broker_secret ))


    - name: tps
      release: capi
      properties:
        capi:
          tps:
            bbs: (( grab meta.diego_bbs_client_tls ))
            cc:  (( grab meta.certs.cf_internal.cc_bridge_tps ))
            watcher:
              skip_consul_lock: true
              locket:
                api_location: "locket.service.cf.internal:8891"

    - name: cc_uploader
      release: capi
      properties:
        capi:
          cc_uploader:
            cc:         (( grab meta.certs.cf_internal.cc_bridge_cc_uploader ))
            mutual_tls: (( grab meta.certs.cf_internal.cc_bridge_cc_uploader_server ))


    - name: scheduler
      release: cf-syslog-drain
      properties:
        scalablesyslog:
          scheduler:
            api:
              url: https://cloud-controller-ng.service.cf.internal:9023
            tls:
              api:
                cn:         "cloud-controller-ng.service.cf.internal"
                .:          (( inject meta.certs.cf_internal.scheduler_api_tls )) # .ca, .cert & .key
              client:
                adapter_cn: "ss-adapter"
                .:          (( inject meta.certs.loggregator.scheduler_client_tls )) # .ca, .cert & .key
