---
instance_groups:
  - name: cell
    jobs:
      - name: rep
        properties:
          containers:
            trusted_ca_certificates: (( grab meta.cell.trusted_cas params.trusted_cas )) # yes, grab concatenates lists
            proxy:
              enabled: true
              require_and_verify_client_certificates: true
              trusted_ca_certificates:
                - (( grab meta.certs.cf_internal.gorouter_backend_tls.ca_cert ))
                - (( grab meta.certs.cf_internal.ssh_proxy_backends_tls.ca_cert ))
              verify_subject_alt_name:
                - gorouter.service.cf.internal
                - ssh-proxy.service.cf.internal

  - name: router
    jobs:
      - name: ssh_proxy
        properties:
          backends:
            tls:
              enabled: true
              ca_certificates:  [ (( grab meta.certs.diego_instance_identity_ca.ca_cert )) ]
              client_certificate: (( grab meta.certs.cf_internal.ssh_proxy_backends_tls.cert ))
              client_private_key: (( grab meta.certs.cf_internal.ssh_proxy_backends_tls.key ))
