---
instance_groups:
  - name: diego-cell
    jobs:
      - name: garden
        properties:
          garden:
            containerd_mode: (( prune ))

      - name: containerd
      - (( delete "containerd" ))
