---
meta:
  cc:
    volume_services_enabled: true

instance_groups:
  - name: cell
    jobs:
      - (( append ))

      - name:    mapfs
        release: mapfs

      - name:    nfsv3driver
        release: nfs-volume

releases:
  - name:    nfs-volume
    version: "2.3.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/nfs-volume-release?v=" releases.nfs-volume.version ))
    sha1:    8e104d7ed5be84258253476784b4d55650504125

  - name:    mapfs
    version: "1.2.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/mapfs-release?v=" releases.mapfs.version ))
    sha1:    0906df6efd4f785baea994c7d8fac9aad64f00b8
